const headers = {
    // --GET --https://www.irctc.co.in/nget/
    headers_1 : {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Connection": "keep-alive",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "none",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\""
    },
    // --GET --https://www.irctc.co.in/eticketing/protected/profile/textToNumber/
    headers_2 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/train-search",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\""
    },
    // --GET --https://www.irctc.co.in/eticketing/protected/mapps1/loginCaptcha
    headers_3 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/train-search",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\""
    },
    // --POST --https://www.irctc.co.in/authprovider/webtoken
    headers_4 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.10",
        "Connection": "keep-alive",
        "Content-Length": "",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/train-search",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\""
    },
    // --GET --https://www.irctc.co.in/eticketing/protected/mapps1/validateUser?source=3
    headers_5 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/train-search",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --POST --https://www.irctc.co.in/eticketing/protected/mapps1/altAvlEnq/TC
    headers_6 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Length": "",
        "Content-Type": "application/json; charset=UTF-8",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/train-search",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --POST --https://www.irctc.co.in/eticketing/protected/mapps1/avlFarenquiry/
    headers_7 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Length": "",
        "Content-Type": "application/json; charset=UTF-8",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/booking/train-list",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --POST --https://www.irctc.co.in/eticketing/protected/mapps1/boardingStationEnq
    headers_8 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Length": "404",
        "Content-Type": "application/json; charset=UTF-8",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/booking/train-list",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --POST --https://www.irctc.co.in/eticketing/protected/mapps1/allLapAvlFareEnq/Y
    headers_9 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Length": "",
        "Content-Type": "application/json; charset=UTF-8",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/booking/psgninput",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --GET --https://www.irctc.co.in/eticketing/protected/mapps1/captchaverify/xxxxx/BOOKINGWS/xxxx
    headers_10 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.8",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/booking/reviewBooking",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --POST --https://www.irctc.co.in/eticketing/protected/mapps1/bookingInitPayment/xxxxxx?insurenceApplicable=
    headers_11 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Length": "",
        "Content-Type": "application/json; charset=UTF-8",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/payment/bkgPaymentOptions",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --POST --https://www.wps.irctc.co.in/eticketing/PaymentRedirect
    headers_12 : {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Cache-Control": "max-age=0",
        "Connection": "keep-alive",
        "Content-Length": "",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.wps.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "same-site",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\""
    },
    // --POST --https://securegw.paytm.in/theia/processTransaction?orderid=422424245242
    headers_13 : {
        'Method': 'POST',
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Cache-Control": "max-age=0",
        "Content-Type": "application/x-www-form-urlencoded",
        "Dnt": "1",
        "Origin": "https://www.wps.irctc.co.in",
        "Referer": "https://www.wps.irctc.co.in/",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "Sec-Ch-Ua-Mobile": "?0",
        "Sec-Ch-Ua-Platform": "\"Windows\"",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "cross-site",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0"
    },
    // --POST --https://secure.paytmpayments.com/theia/api/v1/processTransaction?mid=IRCTCT1248545585&orderId=1000012345679
    headers_14 : {
        'Method': 'POST',
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Content-Length": "",
        "Content-Type": "application/json",
        "Dnt": "1",
        "Origin": "https://securegw.paytm.in",
        "Referer": "https://securegw.paytm.in/",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "Sec-Ch-Ua-Mobile": "?0",
        "Sec-Ch-Ua-Platform": "\"Windows\"",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "cross-site",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0"
    },
    // --POST --https://secure.paytmpayments.com/theia/upi/transactionStatus?MID=IRCTCT12485455856&ORDER_ID=1000012345679
    headers_15 : {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Content-Length": "",
        "Content-Type": "application/x-www-form-urlencoded",
        "Dnt": "1",
        "Origin": "https://securegw.paytm.in",
        "Referer": "https://securegw.paytm.in/",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "Sec-Ch-Ua-Mobile": "?0",
        "Sec-Ch-Ua-Platform": "\"Windows\"",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "cross-site",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0"
    },
    // --POST --https://secure.paytmpayments.com/theia/transactionStatus?MID=IRCTCT12435674&ORDER_ID=1234567890
    headers_16 : {
        'Method': 'POST',
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Cache-Control": "max-age=0",
        "Content-Length": "",
        "Content-Type": "application/x-www-form-urlencoded",
        "Dnt": "1",
        "Origin": "https://secure.paytmpayments.com",
        "Referer": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "Sec-Ch-Ua-Mobile": "?0",
        "Sec-Ch-Ua-Platform": "\"Windows\"",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "same-origin",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0"
    },
    // --POST --https://www.wps.irctc.co.in/eticketing/BankResponse
    headers_17 : {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Cache-Control": "max-age=0",
        "Connection": "keep-alive",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.wps.irctc.co.in",
        "Origin": "https://secure.paytmpayments.com",
        "Referer": "https://secure.paytmpayments.com/",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "cross-site",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\""
    },
    // --GET --https://www.irctc.co.in/nget/booking-confirm
    headers_18 : {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Cache-Control": "max-age=0",
        "Connection": "keep-alive",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "https://secure.paytmpayments.com/",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "cross-site",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\""
    },
    // --GET --https://www.wps.irctc.co.in/eticketing/protected/mapps1/bookingData/xxxxx
    headers_19 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.wps.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-site",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --GET --https://www.irctc.co.in/eticketing/protected/mapps1/recentTxnsDetails
    headers_20 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/train-search",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\""
    },
    // --GET --https://www.irctc.co.in/eticketing/protected/mapps1/pnrenq/484545545457?pnrEnqType=E
    headers_21 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/txn/my-transactions?page=Booked%20Ticket%20History&eWallet=false",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --GET --https://www.irctc.co.in/eticketing/protected/mapps1/historySearchByTxnId/125510254522?currentStatus=L
    headers_22 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "spa-csrf-token": ""
    },
    // --POST --https://www.wps.irctc.co.in/eticketing/protected/mapps1/verifyPayment/swwedsw
    headers_23 : {
        "Accept": 'application/json, text/plain, */*"',
        "Accept-Encoding": "gzip, deflate, br, zstd",
        'Accept-Language': 'en-US,en;q=0.0',
        'Authorization': "",
        'Connection': 'keep-alive',
        'Content-Language': 'en',
        'Content-Length': "",
        'Content-Type': 'application/json; charset=UTF-8',
        'DNT': '1',
        'Host': 'www.wps.irctc.co.in',
        'Origin': 'https://www.irctc.co.in',
        'Referer': 'https://www.irctc.co.in/',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-site',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0',
        'bmirak': 'webbm',
        'bmiyek': "",
        'greq': "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'spa-csrf-token': ""
    },
    // --GET --https://www.irctc.co.in/eticketing/protected/mapps1/masterpsgnlistenquiry
    headers_24 : {
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Type": "application/x-www-form-urlencoded",
        "DNT": "1",
        "Host": "www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/nget/booking/train-list",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"'
    },
    // --OPTIONS --https://www.wps.irctc.co.in/eticketing/protected/mapps1/verifyPayment/xxxxxx
    headers_25 : {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.9",
        "Access-Control-Request-Headers": "authorization,bmirak,bmiyek,content-type,greq,spa-csrf-token",
        "Access-Control-Request-Method": "POST",
        "Connection": "keep-alive",
        "Host": "www.wps.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-site",
        "User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0'
    },
    // --POST --https://www.wps.irctc.co.in/eticketing/protected/mapps1/verifyPayment/xxxxxx
    headers_26 :{
        "Accept": "application/json, text/plain, */*",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Accept-Language": "en-US,en;q=0.0",
        "Authorization": "",
        "Connection": "keep-alive",
        "Content-Language": "en",
        "Content-Length": "",
        "Content-Type": "application/json; charset=UTF-8",
        "DNT": "1",
        "Host": "www.wps.irctc.co.in",
        "Origin": "https://www.irctc.co.in",
        "Referer": "https://www.irctc.co.in/",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-site",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
        "bmirak": "webbm",
        "bmiyek": "",
        "greq": "",
        "sec-ch-ua": '"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "Windows",
        "spa-csrf-token": "",
    }
};
export {headers};
export default headers;